# Generated by Django 2.2.3 on 2019-07-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
